# Generated by Django 4.0.2 on 2022-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='color',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
